version: '3.4'

# sudo docker-compose up

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - /tmp/redis:/var/lib/redis/
    network_mode: host
  mongodb:
    image: mongodb/mongodb-community-server:6.0.1-ubi8
    ports:
      - '27017:27017'
    network_mode: host
  api:
    # image: reecepbcups/craft-rest-api:1.0.0
    build: .
    depends_on:
      - redis
      - mongodb
    ports:
      - '4000:4000'
    network_mode: host
    environment:
      - DAO_EXP_MODULE_ONLY=false
      - API_PORT=4000
      - REDIS_CONN_STRING=redis://127.0.0.1:6379/0
      - CRAFTD_REST=http://127.0.0.1:1317
      - CRAFTD_NODE=http://127.0.0.1:26657
      - DAO_WALLETS=cosmos10r39fueph9fq7a6lgswu4zdsg8t3gxlqvvvyvn
      - CRAFT_ADMIN_WALLET=cosmos1efd63aw40lxf3n4mhf7dzhjkr453axur6cpk92
      # other
      - DB_CONN_STRING=mongodb://127.0.0.1:27017
      - DB_NAME=crafteconomy
      - CRAFT_DAO_ESCROW_WALLET_MNUMONIC="decorate bright ozone fork gallery riot bus exhaust worth way bone indoor calm squirrel merry zero scheme cotton until shop any excess stage laundry"
      - CRAFT_DAO_ESCROW_SECRET=7821719493
      - CRAFT_DAO_ESCROW_WEBHOOK_URL="https://discord.com/api/webhooks/1304865046232301598/bHfg00PpwwHr63B4IsK7IzWqjrKxhL8x8IJ2k4cFq7-TnRIstooVYoPudYLuX5XtNa-M"
      # If we also wanted to allow offerings via this too, we could for the API
      - ADDR721_REALESTATE="craft1wl59k23zngj34l7d42y9yltask7rjlnxgccawc7ltrknp6n52fpsaug5jn"
      - ADDR721_SKINS="craft1dt3lk455ed360pna38fkhqn0p8y44qndsr77qu73ghyaz2zv4whqgg28q2"
      - ADDRM="craft1fkwjqyfdyktgu5f59jpwhvl23zh8aav7f98ml9quly62jx2sehys8t86pv"
